# Generated by Django 2.0 on 2021-03-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('lot', models.CharField(blank=True, max_length=20, null=True)),
                ('detailing_type', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
