# Generated by Django 3.0.5 on 2021-03-30 13:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=4, max_digits=8)),
                ('lot', models.DecimalField(decimal_places=4, max_digits=8)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone_offset', models.CharField(blank=True, max_length=20, null=True)),
                ('minutely', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), size=8)),
                ('hourly', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), size=8)),
                ('daily', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), size=8)),
            ],
            options={
                'db_table': 'weather',
            },
        ),
        migrations.DeleteModel(
            name='Weather_info',
        ),
    ]
