# Generated by Django 3.0.5 on 2021-03-30 13:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210330_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherinfo',
            name='daily',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=8),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='hourly',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=8),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='minutely',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=8),
        ),
    ]
