# Generated by Django 3.0.5 on 2021-03-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210331_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherinfo',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
