# Generated by Django 3.0.5 on 2021-03-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20210330_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherinfo',
            old_name='lot',
            new_name='lon',
        ),
    ]
