# Generated by Django 3.0.5 on 2021-03-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_weatherinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherinfo',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
